name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:18.04

    strategy:
      matrix:
        include:
          - ONEAPI_VERSION: "2025.2"
            SYCL_VERSION: "6.2.1"
          - ONEAPI_VERSION: "2025.3"
            SYCL_VERSION: "6.3.0"

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y gcc g++ libhwloc-dev python3 git ca-certificates wget gnupg libtinfo5 cmake
          wget --no-verbose -O /cuda-keyring_1.1-1_all.deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          dpkg -i /cuda-keyring_1.1-1_all.deb
          apt-get update
          apt-get install -y cuda-toolkit-12-2
          echo "PATH=/usr/local/cuda-12.2/bin:${PATH}" >> ${GITHUB_ENV}
          echo "LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64:${LD_LIBRARY_PATH}" >> ${GITHUB_ENV}

      - name: Checkout
        run: |
          git config --global --add safe.directory '*'
          git init
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git fetch --depth=1 origin ${GITHUB_REF}
          git checkout FETCH_HEAD

      - name: Build
        # The sed command is an hacky workaround but gets the job done for now
        run: |
          sed -i 's/^COMPILER_VERSION="2025\.3"$/COMPILER_VERSION="${{ matrix.ONEAPI_VERSION }}"/' ./oneapi-ur-adapter.stub.sh
          python3 build_adapter.py \
            --cuda \
            --branch v${{ matrix.SYCL_VERSION }} \
            --oneapi-version ${{ matrix.ONEAPI_VERSION }} \
            --stub ./oneapi-ur-adapter.stub.sh \
            -j$(nproc)
      
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: oneapi-ur-cuda-linux-x86_64-${{ matrix.ONEAPI_VERSION }}.sh
          path: work_ur_build/out/

  release:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: collected-artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: collected-artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
